name: Mise

on:
  push:
    branches:
      - main

jobs:
  mise:
    runs-on: ubuntu-latest
    env:
      MISE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Mise
        uses: ./.github/actions/mise

      - run: |
          node -v
          python --version
